"""initial_schema

Revision ID: 34047d11e84a
Revises: 
Create Date: 2026-03-14 17:21:58.586241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34047d11e84a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_current', sa.Integer(), nullable=False),
    sa.Column('streak_longest', sa.Integer(), nullable=False),
    sa.Column('streak_last_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('ocr_engine_used', sa.String(length=30), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cards_created', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_status'), ['status'], unique=False)

    op.create_table('user_achievements',
    sa.Column('achievement_key', sa.String(length=100), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_key'], ['achievements.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('achievement_key')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('thai', sa.Text(), nullable=False),
    sa.Column('romanization', sa.Text(), nullable=True),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('example_thai', sa.Text(), nullable=True),
    sa.Column('example_english', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('source_upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_upload_id'], ['uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_deck_id'), ['deck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_thai'), ['thai'], unique=False)

    op.create_table('card_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_media_card_id'), ['card_id'], unique=False)

    op.create_table('card_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('fsrs_stability', sa.Float(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsrs_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fsrs_reps', sa.Integer(), nullable=False),
    sa.Column('fsrs_lapses', sa.Integer(), nullable=False),
    sa.Column('fsrs_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'direction', name='uq_card_direction')
    )
    with op.batch_alter_table('card_schedules', schema=None) as batch_op:
        batch_op.create_index('idx_schedules_due', ['fsrs_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_schedules_card_id'), ['card_id'], unique=False)

    op.create_table('card_tags',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'tag_id'),
    sa.UniqueConstraint('card_id', 'tag_id', name='uq_card_tag')
    )
    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_before', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['card_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_log_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_log_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_log_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_review_log_reviewed_at'))

    op.drop_table('review_log')
    with op.batch_alter_table('card_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_tags_tag_id'))

    op.drop_table('card_tags')
    with op.batch_alter_table('card_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_schedules_card_id'))
        batch_op.drop_index('idx_schedules_due')

    op.drop_table('card_schedules')
    with op.batch_alter_table('card_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_media_card_id'))

    op.drop_table('card_media')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_thai'))
        batch_op.drop_index(batch_op.f('ix_cards_deck_id'))

    op.drop_table('cards')
    op.drop_table('user_achievements')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_status'))

    op.drop_table('uploads')
    op.drop_table('user_profile')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    op.drop_table('decks')
    op.drop_table('achievements')
    # ### end Alembic commands ###
